---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatagent.fullname" . }}
  labels:
    {{- include "chatagent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "chatagent.config" . | nindent 4 }}
