{{- if .Values.devsecops.AuthorizationPolicy.rules }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "customer-mcp.fullname" . }}
  labels:
    {{- include "customer-mcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "customer-mcp.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  {{-  tpl (toYaml .Values.devsecops.AuthorizationPolicy.rules) . | nindent 4 }}
{{- end }}
