---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-mcp.fullname" . }}
  labels:
    {{- include "customer-mcp.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "customer-mcp.config" . | nindent 4 }}
