env: {}

replicaCount: 1

lifecycle: {}
#   preStop:
#     httpGet:
#       port: http-web
#       path: "/"

livenessProbe:
  tcpSocket:
    port: http-web
  periodSeconds: 30
  initialDelaySeconds: 10

readinessProbe:
  tcpSocket:
    port: http-web
  periodSeconds: 5

image:
  repository: ghcr.io/polecatworks/chatagent-root-m365agentsplayground
  tag: main
  pullPolicy: Always

imagePullSecrets:
  - name: dockerconfigjson-ghcr-io

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 56150

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configs: {}

args:
  - "-p"
  - "56150"
  - "-e"
  - "http://chatagent/api/messages"
  - "-c"
  - "emulator"

secretName: null

volumes: []
#   - name: configs
#     configMap:
#       name: '{{ template "m365agentsplayground.fullname" . }}'

volumeMounts: []
#   - name: configs
#     mountPath: /opt/app/configs

devsecops:
  RequestAuthentication:
    jwtRules: []
  AuthorizationPolicy:
    rules: []
