{{- $volumesha := tpl (toYaml .Values.volumes) . | sha256sum }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "m365agentsplayground.fullname" . }}
  labels:
    {{- include "m365agentsplayground.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "m365agentsplayground.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/volumes: {{ $volumesha }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "m365agentsplayground.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "m365agentsplayground.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.volumes }}
      volumes: {{- include "m365agentsplayground.volumes" . | nindent 8 }}
      {{- end }}
      containers:
        - name: m365agentsplayground
          env: {{- include "m365agentsplayground.env" . | nindent 12 }}
          {{- with .Values.command }}
          command: {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts: {{- include "m365agentsplayground.volumeMounts" . | nindent 10 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-web
              containerPort: {{ .Values.service.targetPort | default 56150 }}
              protocol: TCP
          {{- if .Values.lifecycle }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
