apiVersion: v1
kind: Service
metadata:
  name: {{ include "m365agentsplayground.fullname" . }}
  labels:
    {{- include "m365agentsplayground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{ toYaml .Values.service.sessionAffinityConfig | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http-web
      protocol: TCP
      name: http-web
  selector:
    {{- include "m365agentsplayground.selectorLabels" . | nindent 4 }}
